Pages/Pokemons/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using repeatRazorPages.Data;
using repeatRazorPages.Model;

namespace repeatRazorPages.Pages.Pokemons;

public class DeleteModel(PokemonContext pokemonContext) : PageModel
{
    public Pokemon? Pokemon { get; set; }
    public async Task OnGetAsync(int id)
    {
        Pokemon =await pokemonContext.Pokemons.FirstAsync(pokemon => pokemon.Id == id);
        
    }

    public async Task <IActionResult> OnPostDeleteAsync(int id)
    {
        var pokemon = await pokemonContext.Pokemons.FirstAsync(pokemon => pokemon.Id == id);
        pokemonContext.Pokemons.Remove(pokemon);

        await pokemonContext.SaveChangesAsync();
        return RedirectToPage("./Index");
	}
}

Pages/Pokemons/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using repeatRazorPages.Data;
using repeatRazorPages.Model;

namespace repeatRazorPages.Pages.Pokemons;

public class DetailsModel(PokemonContext pokemonContext) : PageModel
{
    public Pokemon? Pokemon { get; set; }
    public async Task OnGetAsync(int id)
    {
        Pokemon = await pokemonContext.Pokemons.FirstAsync(pokemon => pokemon.Id == id);

        

    }
}

Pages/Pokemons/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using repeatRazorPages.Data;
using repeatRazorPages.Model;

namespace repeatRazorPages.Pages.Pokemons;

public class EditModel (PokemonContext pokemonContext) : PageModel
{
	[BindProperty]
	public Pokemon? Pokemon { get; set; }
	public async Task OnGetAsync(int id)
    {
		Pokemon = await pokemonContext.Pokemons.FirstAsync(pokemon => pokemon.Id == id);
	}

	public async Task<IActionResult> OnPostUpdateAsync(int id)
	{
		if (!ModelState.IsValid)
		{
			return Page();
		}

        var updatedPokemon = await pokemonContext.Pokemons.FirstAsync(pokemon => pokemon.Id == id);

		updatedPokemon.Name = Pokemon.Name;
		updatedPokemon.URL = Pokemon.URL;
		updatedPokemon.Description = Pokemon.Description;
		updatedPokemon.Level = Pokemon.Level;
		await pokemonContext.SaveChangesAsync();

        return RedirectToPage("./Index");
	}
}

Pages/Pokemons/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using repeatRazorPages.Data;
using repeatRazorPages.Model;

namespace repeatRazorPages.Pages.Pokemons
{
    public class IndexModel(PokemonContext pokemonContext) : PageModel        
    {
        public IEnumerable <Pokemon> Pokemons { get; set; } = pokemonContext.Pokemons;
       


        public void OnGet()
        {
            ViewData["Title"] = "pokemons";
        }
        [BindProperty]
        public string? SearchNamePokemon {  get; set; }

        public async Task  OnPostAsync() 
        {
            if (SearchNamePokemon is null)
            {
                return;
            }
            Pokemons=await pokemonContext.Pokemons.Where(pokemon=>pokemon.Name.Contains(SearchNamePokemon)).ToListAsync();
        }
        
    }
}

Pages/PokemonsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.VisualBasic;
using repeatRazorPages.Model;

namespace repeatRazorPages.Pages;

public class PokemonsPageModel : PageModel
{
    public void OnGet()
    {
        ViewData["Title"] = "Pokedex";
    }
    [BindProperty]
    public Pokemon? myPokemon { get; set; }

    public IActionResult OnPost()
    {
        if (myPokemon is not null && ModelState.IsValid)
        {
            //PokemonStorege.Pokemons.Add(myPokemon);       
			return RedirectToPage("/PokemonsPage");
		}
        return Page();
    }
    //public IActionResult OnPost()
    //{
    //    if (myPokemon is not null && ModelState.IsValid) 
    //    { 
    //        PokemonStorege.Pokemons.Add(myPokemon);
    //        return RedirectToPage("/PokemonsPage");
    //    }
    //    return Page();
    //}
}

Pages/Shared/_Layout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace repeatRazorPages.Pages.Shared
{
    public class _LayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/_ViewStart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace repeatRazorPages.Pages
{
    public class _ViewStartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model repeatRazorPages.Pages.IndexModel


<div class="container">
    <h1>Добро пожаловать на сайт посвященный Покéмонам</h1>
    <h2 style="text-align: center;">На данном ресурсе вы можете ознакомиться с различными покéмонами, а так же пополнять нашу базу покéмонов!</h2> 
</div>    

Pages/Pokemons/Add.cshtml
@page
@using repeatRazorPages.Pages.Pokemons
@model AddModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form method="post">
	<div>
		<label>Имя покемона</label>
		<input asp-for="Pokemon.Name" type="text" />
		<span asp-validation-for="Pokemon.Name" class="text-danger"></span>
	</div>
	<div>
		<label>ссылка на фото</label>
		<input asp-for="Pokemon.URL" type="text" />
		<span asp-validation-for="Pokemon.URL" class="text-danger"></span>
	</div>
	<div>
		<label>описание</label>
		<input asp-for="Pokemon.Description" type="text" />
		<span asp-validation-for="Pokemon.Description" class="text-danger"></span>
	</div>
	<div>
		<label>уровень</label>
		<input asp-for="Pokemon.Level" type="text" />
		<span asp-validation-for="Pokemon.Level" class="text-danger"></span>
	</div>
	<input type="submit"/>

</form>

Pages/Pokemons/Delete.cshtml
@page
@using repeatRazorPages.Pages.Pokemons
@model DeleteModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container">
	<form method="post">
		<h1>вы уверены что хотите удалить этого покемона @Model.Pokemon.Name</h1>
		<p>Описание: @Model.Pokemon.Description</p>
		<p>Уровень: @Model.Pokemon.Level</p>
		<div>
			<button type="submit" asp-route-id="@Model.Pokemon.Id" asp-page-handler="delete" class="btn btn-primary">Удалить</button>
		</div>
		
	</form>
</div>

Pages/Pokemons/Details.cshtml
@page
@using repeatRazorPages.Pages.Pokemons
@model DetailsModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="cd__main">
	<div class="container my-5">
		<div class="row">
			<div class="col-md-5">
				<div class="main-img">
					<img class="img-fluid" src="@Model!.Pokemon!.URL" alt="@Model.Pokemon.Name">
				</div>
			</div>
			<div class="col-md-7">
				<div class="main-description px-2">
					<div class="category text-bold">
						Название: @Model.Pokemon.Name
					</div>
					<div class="product-title text-bold my-3">
						Описание: @Model.Pokemon.Description
					</div>
					<div class="price-area my-4">
						Уровень покемона: @Model.Pokemon.Level
					</div>
					<a class="btn btn-primary" asp-page="./Index">Назад</a>
				</div>
			</div>
		</div>

	</div>
</div>

Pages/Pokemons/Edit.cshtml
@page
@using repeatRazorPages.Pages.Pokemons
@model EditModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<form method="post">

	<div hidden ="hidden">		
		<input asp-for="Pokemon.Id" type="number" />
	</div>
	<div>
		<label>имя</label>
		<input asp-for="Pokemon.Name" type="text"/>
		<span asp-validation-for="Pokemon.Name" class="text-danger"></span>
	</div>
	<div>
		<label>ссылка на фото</label>
		<input asp-for="Pokemon.URL" type="text" />
		<span asp-validation-for="Pokemon.URL" class="text-danger"></span>
	</div>
	<div>
		<label>описание</label>
		<input asp-for="Pokemon.Description" type="text" />
		<span asp-validation-for="Pokemon.Description" class="text-danger"></span>
	</div>
	<div>
		<label>уровень</label>
		<input asp-for="Pokemon.Level" type="text" />
		<span asp-validation-for="Pokemon.Level" class="text-danger"></span>
	</div>
	<button type="submit" asp-route-id="@Model.Pokemon.Id" asp-page-handler="update" class="btn btn-primary">обновить</button>

</form>

Pages/Pokemons/Index.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using repeatRazorPages.Pages.Pokemons
@model IndexModel


<div class="container" style="padding-top: 35px">

    <div class="d-flex justify-content-center mb-3">
        <a asp-page="/Pokemons/Add" class="btn btn-success">Добавить</a>
    </div>
    <form method="post">
        <p>Поиск
            <input type="text" asp-for="SearchNamePokemon" value=""/>
            <input type="submit" />
        </p>
    </form>
    <div class="d-flex flex-wrap justify-content-center">
        @foreach (var pokemon in @Model.Pokemons)
        {
            <div class="card m-2" style="width: 18rem; height: 22rem;">
                <img src="@pokemon.URL" class="card-img-top" alt="@pokemon.Name" style="height: 10rem; object-fit: cover;">
                <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title" style="height: 3rem; overflow: hidden;">Имя: @pokemon.Name</h5>
                    <p class="card-text" style="height: 3rem; overflow: hidden;">Уровень: @pokemon.Level</p>
                    <div method="post" class="d-flex justify-content-between">
                        <a asp-page="/Pokemons/Details" asp-route-id="@pokemon.Id" class="btn btn-primary">Инфо</a>
                        <a asp-page="/Pokemons/Delete" asp-route-id="@pokemon.Id" class="btn btn-primary">удалить</a>
						@* <button type="submit" asp-route-id="@pokemon.Id" asp-page-handler="delete" class="btn btn-primary">Удалить</button>
                         <a asp-page="/Pokemons/Edit" asp-route-id="@pokemon.Id" class="btn btn-primary">Редактировать</a> *@
                    </div>
                    <div>
                        <a asp-page="/Pokemons/Edit" asp-route-id="@pokemon.Id" class="btn btn-primary">редактировать</a>
                    </div>

                </div>
            </div>
        }
    </div>
</div>

Pages/PokemonsPage.cshtml
@page

@model repeatRazorPages.Pages.PokemonsPageModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container">
    <div class="row justify-content-center">
        <div class="d-flex flex-wrap justify-content-center">
           @*  @foreach (var pokemon in PokemonStorege.Pokemons)
            {
                <div class="card m-2" style="width: 18rem;">
                    <img src="@pokemon.URL" class="card-img-top" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@pokemon.Name</h5>
                        <p class="card-text">@pokemon.Description</p>
                        <p class="card-text">@pokemon.Level</p>
                        <a href="#" class="btn btn-primary">Купить</a>
                    </div>
                </div>
            } *@
        </div>
    </div>

    <div class="row justify-content-center">
        <p>Создание нового покемончика<br /></p>
        <form method="post" class="col-6">
            <div class="form-group">
                <input asp-for="myPokemon.Name" type="text" class="form-control" placeholder="Введите имя покемона" />
            </div>
            <div class="form-group">
                <input asp-for="myPokemon.URL" type="text" class="form-control" placeholder="Введите адрес картинки" />
            </div>
            <div class="form-group">
                <input asp-for="myPokemon.Description" type="text" class="form-control" placeholder="Введите описание" />
            </div>
            <div class="form-group">
                <input asp-for="myPokemon.Level" type="text" class="form-control" placeholder="Введите уровень покемона" />
            </div>
            <input type="submit" class="btn btn-primary">
        </form>
    </div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">

<head>
	<!-- требуемые мета-теги -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=l, shrink-to-fit=no" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
	<title>@ViewData["Title"]</title>
</head>

<body>
    <!-- Навигационное меню (navbar) -->    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Pokémon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="Pokemons">Pokédex</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Types</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Regions</a>
                </li>
            </ul>
        </div>
    </nav>

	<div class="container">
		@RenderBody()
		<hr />
		@* <footer>
			<p>Copyright &copy; 2024 @ViewData["Title"]</p>
		</footer> *@
	</div>
	<!-- JavaScript-код для включения таких функций, как карусель -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
			integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslKleN7N6jIeHz"
			crossorigin="anonymous"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>